config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :sites
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
	require 'open-uri'
	require 'fastimage'
	require 'nokogiri'

	has_many :users_sites
	has_many :users, through: :users_sites

	def self.update_all
		Site.all.each do |site|
			puts site.site_url
			site.update_database_entry(site)
		end
	end
	
	def self.spawn(site)
		nokogiri = Nokogiri::HTML(open(site))
		new_site = Site.new
		data_set = new_site.data_hash(site, nokogiri)
		new_site = Site.new(data_set)
		new_site.find_image_from_site(new_site, nokogiri)
		new_site.save
	end
	
	def data_hash(site, nokogiri)
		site_data = {
			site_url: site,
			picture_url: get_biggest_picture(site, get_domain(site), nokogiri)[1],
			orig_pic_url: get_biggest_picture(site, get_domain(site), nokogiri)[0],
			domain: get_domain(site),
			title: get_title(nokogiri)
		}
	end

	def image_size(picture)
		FastImage.size(picture) != nil ? FastImage.size(picture).inject(:*) : 0
	end

	def get_biggest_picture(site, domain, nokogiri)
		image_elements = nokogiri.search('img')
		@images = image_elements.map{ |item| item.attributes["src"].value }
		indexed_images = @images.each_with_index.map{|img, index| [index, url_shortener_filter(img, domain)]}
		domain_filter = domain_filter(domain, indexed_images)
		w_filter = domain_filter.select{|img| wonder_filter(img[1])}
		w_filter.map!{|img| [img[0], http_filter(img[1])]}
		w_filter.sort!{|a,b| image_size(b[1]) <=> image_size(a[1])}
		winning_combo = w_filter.first
		winning_combo = [@images[winning_combo[0]], winning_combo[1]]
		winning_combo
	end

	def get_domain(site)
		site[/(?<=\.)[^_]+(?=\.)/]
	end

	def get_title(nokogiri)
		nokogiri.search('title').children[0].text
	end

	def class_id_formatter(site)
		classes = site.classes == nil ? "" : ".#{site.classes}"
		ids = site.ids == nil ? "" : "##{site.ids}"
		"#{site.container}#{classes}#{ids}"
	end

	def update_database_entry(site)
		search_query = site.class_id_formatter(site)
		doc = Nokogiri::HTML(open(site.site_url)).search(search_query)
		new_image = site.container != "img" ? doc.search('img')[0]['src'] : doc[0]['src']
		site.orig_pic_url = new_image
		site.picture_url = site.filter_package(site)
		site.save
	end

	def find_image_from_site(site, nokogiri)
		doc = nokogiri.search('img')
		image = doc.select{|img|img.attributes['src'].value == site.orig_pic_url}[0]
		site.class_id_container_parent(site, image)
	end

	def class_id_container_parent(site, nokogiri)
		until site.class_or_id_labeled(nokogiri)
			nokogiri = nokogiri.parent
		end
		site.update_site(site, nokogiri)
	end

	def class_or_id_labeled(nokogiri)
		nokogiri.attributes.include?("class") || nokogiri.attributes.include?("id")
	end

	def update_site(site, nokogiri)
		site.classes = nokogiri["class"]
		site.ids = nokogiri["id"]
		site.container = nokogiri.name
		site.save
	end

	def url_shortener_filter(site, domain)
		site.include?('..') ? ("http://www." + domain + ".com" + site[/(?<=\.\.).*/]) : site
	end

	def domain_filter(domain, sites)
		filtered = sites.select{|site| site[1].include? domain}
		filtered != [] ? filtered : sites
	end

	def wonder_filter(site)
		!site.include?('projectwonderful')
	end

	def http_filter(site)
		site.include?('https:') || site.include?('http:') ? site : "http:#{site}"
	end

	def filter_package(site)
		domain = site.domain
		url = site.orig_pic_url
		url_shortened = url_shortener_filter(url, domain)
		domain_filtered = domain_filter(domain, [[0,url_shortened]])
		http_filtered = http_filter(domain_filtered[0][1])
		http_filtered
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  require 'open-uri'
  require 'fastimage'
  require 'nokogiri'
    # respond_to :html, :js


  def index
    # puts "Helloohise0he0h8et40h8eth90erth90et490het490hjerg90hrg90hgr90hgre90hrgh09"
    @sites = Site.all
    # require pry; binding.pry
    # puts "h80se80hsf8g0sef08gsfe08gfse80gfes80gsef08gefs0g8esf"
  end

  def show
    @site = Site.all.sample
  end

  def create
    site = site_params[:site]
    domain = domain(@site)
    image = get_biggest_picture(@site, @domain)
    title = title(@site)
    Site.new(site_url: site, picture_url: image, domain: domain, title: title)
  end

  def image_size(picture)
    FastImage.size(picture) != nil ? FastImage.size(picture).inject(:*) : 0
  end

  def get_biggest_picture(site, domain)
    image_elements = Nokogiri::HTML(open(site)).search('img')
    images = image_elements.map{ |item| item.attributes["src"].value }
    images.map!{|img| url_shortener_filter(img, domain)}
    domain_filter = domain_filter(domain, images)
    w_filter = domain_filter.select{|img| wonder_filter(img)}
    w_filter.map!{|img| http_filter(img)}
    w_filter.sort!{|a,b| image_size(b) <=> image_size(a)}
    w_filter.first
  end

  def domain(site)
    site[/(?<=\.)[^_]+(?=\.)/]
  end

  def title(site)
    Nokogiri::HTML(open(site)).search('title').children[0].text
  end

  def wonder_filter(site)
    !site.include?('projectwonderful')
  end

  def domain_filter(domain, sites)
    filtered = sites.select{|site| site.include? domain}
    filtered != [] ? filtered : sites
  end

  def http_filter(site)
    site.include?('http:') ? site : "http:#{site}"
  end

  def url_shortener_filter(site, domain)
    site.include?('..') ? ("http://www." + domain + ".com" + site[/(?<=\.\.).*/]) : site
  end


  private

   def site_params
    params.require(:site).permit(:site_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<%= form_tag '/pictures', method: 'get' do %>
<%= text_field_tag :site, nil, value: 'http://' %>
<%= submit_tag 'Get Sites' %>
<% end %>

<div class = 'images'>
  <% @sites.each do |site| %>
  <div class = '<%=site.id%>'>
    <a href = <%= site.site_url %> >
      <%= site.title %>
    </a>
    
    <br>
    <a href = <%= site.site_url %> >

      <img src = <%= site.picture_url %> >
    </a>
  </div>
  <% end %>
</div>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>